export type Recipe = {
  id: string;
  title: string;
  short: string;
  description: string;
  timeMin: number;
  difficulty: "Lako" | "Srednje" | "Teško";
  category: "vegan" | "proteinsko" | "tradicionalno";
  isPremium: boolean;
  priceRsd?: number;
  imageUrl?: string;
  ingredients: string[];
  steps: string[];
};

export const RECIPES: Recipe[] = [
  {
    id: "pasta-carbonara",
    title: "Pasta Carbonara",
    short: "Kremasta pasta bez pavlake: jaja + sir + slanina + brza tehnika mešanja.",
    description: "Brza italijanska pasta sa jajima, sirom i slaninom.",
    timeMin: 20,
    difficulty: "Lako",
    category: "tradicionalno",
    isPremium: false,
    imageUrl: "https://images.unsplash.com/photo-1608756687911-aa1599ab3bd9?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ingredients: ["200g paste", "2 jaja", "100g slanine", "50g parmezana", "So, biber"],
    steps: [
      "Skuvati pastu u slanoj vodi.",
      "Ispržiti slaninu dok ne postane hrskava.",
      "Umutiti žumanca i parmezan.",
      "Pomešati pastu sa slaninom i skloniti sa vatre.",
      "Dodati smesu od jaja i brzo promešatina tihoj vatri.",
    ],
  },
  {
    id: "sarma",
    title: "Sarma",
    short: "Kupus + meso + pirinač, dugo krčkanje na tihoj vatri.",
    description: "Tradicionalna sarma — klasika.",
    timeMin: 180,
    difficulty: "Teško",
    category: "tradicionalno",
    isPremium: true,
    priceRsd: 299,
    imageUrl: "https://www.mojrecept.rs/sites/default/files/styles/home_stage_1500_700/public/srh_recipes/68bd3c4e6e031693559c483e7fa607bf.png?h=db276b92&itok=9zghAh-p",
    ingredients: ["Kiseli kupus", "500g mlevenog mesa", "Pirinač", "Crni luk", "So, biber"],
    steps: [
      "Umešati meso, pirinač i začine.",
      "Uviti smesu u listove kupusa.",
      "Kuvati na tihoj vatri oko 3 sata.",
    ],
  },
  {
    id: "gulas",
    title: "Domaći gulaš",
    short: "Sporo kuvanje za pun ukus: luk + meso + začini, krčka se dugo.",
    description: "Domaći gulaš koji se krčka polako i bude top.",
    timeMin: 120,
    difficulty: "Srednje",
    category: "tradicionalno",
    isPremium: false,
    imageUrl:"https://n1info.rs/media/images/1695381770-shutterstock_16392860.format-webp.width-1200.webp",
    ingredients: ["600g mesa (junetina/svinjetina)", "2 glavice luka", "Aleva paprika", "So, biber", "Lovor"],
    steps: [
      "Prodinstati luk dok ne omekša.",
      "Dodati meso i zapeći sa svih strana.",
      "Dodati začine i malo vode.",
      "Krčkati 1.5–2h uz povremeno dolivanje vode.",
    ],
  },
  {
    id: "pasulj-prebranac",
    title: "Prebranac",
    short: "Pasulj zapečen u rerni sa lukom i paprikom — klasično jelo.",
    description: "Zapečeni pasulj sa lukom i začinima, odličan i sutradan.",
    timeMin: 90,
    difficulty: "Srednje",
    category: "tradicionalno",
    isPremium: true,
    priceRsd: 249,
    imageUrl:"https://recepti.zena.blic.rs/resources/images/ae/aecb41b9c3add9b0c3c21cbbb6bf26fa/resize/f729eb4f2f7c7422095f6914cb8e2281_670x0.jpg",
    ingredients: ["Pasulj", "2 glavice luka", "Aleva paprika", "Lovor", "So, biber", "Ulje"],
    steps: [
      "Skuvati pasulj (ili koristiti već kuvani).",
      "Prodinstati luk, dodati alevu papriku.",
      "Pomešati pasulj i luk, prebaciti u pleh.",
      "Zapeći 30–40 min na 200°C.",
    ],
  },
  {
    id: "pileca-salata",
    title: "Pileća salata",
    short: "Brz proteinski obrok: piletina + salata + maslinovo ulje.",
    description: "Proteinska salata sa piletinom, povrćem i dresingom.",
    timeMin: 15,
    difficulty: "Lako",
    category: "proteinsko",
    isPremium: false,
    imageUrl: "https://images.unsplash.com/photo-1580013759032-c96505e24c1f?w=1200&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpY2tlbiUyMHNhbGFkfGVufDB8fDB8fHww",
    ingredients: ["200g pilećeg filea", "Zelena salata", "Paradajz", "Maslinovo ulje"],
    steps: ["Ispeći piletinu na tiganju.", "Iseckati povrće.", "Sve sjediniti i dodati dresing."],
  },
  {
    id: "losos-sa-povrcem",
    title: "Losos sa povrćem",
    short: "Pečeni losos + povrće iz rerne, jako zasitno i zdravo.",
    description: "Pečeni losos bogat proteinima uz sezonsko povrće.",
    timeMin: 35,
    difficulty: "Srednje",
    category: "proteinsko",
    isPremium: true,
    priceRsd: 349,
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ingredients: ["File lososa", "Tikvice", "Paprika", "Maslinovo ulje", "So, biber"],
    steps: ["Začiniti lososa.", "Ispeći u rerni 20 minuta.", "Ispeći povrće i poslužiti zajedno."],
  },
  {
    id: "jaja-avokado-toast",
    title: "Proteinski tost sa jajima i avokadom",
    short: "Doručak za 10 min: tost + jaja + avokado.",
    description: "Brz i zasitan doručak pun proteina.",
    timeMin: 10,
    difficulty: "Lako",
    category: "proteinsko",
    isPremium: false,
    imageUrl: "https://plus.unsplash.com/premium_photo-1676106623583-e68dd66683e3?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ingredients: ["2 jaja", "1 avokado", "Integralni hleb", "So, biber"],
    steps: ["Ispeći jaja.", "Izgnječiti avokado.", "Sve staviti na tost i začiniti."],
  },
  {
    id: "wrap-od-tunjevine",
    title: "Wrap od tunjevine",
    short: "Tunjevina + grčki jogurt + povrće u tortilji — brz proteinski ručak.",
    description: "Proteinski wrap koji se sprema brzo i lako.",
    timeMin: 12,
    difficulty: "Lako",
    category: "proteinsko",
    isPremium: true,
    priceRsd: 199,
    imageUrl:"https://www.eatyourselfskinny.com/wp-content/uploads/2025/02/Spicy-Tuna-Wrap-1.jpg",
    ingredients: ["1 konzerva tunjevine", "2 kašike grčkog jogurta", "Tortilja", "Zelena salata", "Krastavac", "So, biber"],
    steps: ["Pomešati tunjevinu i grčki jogurt, začiniti.", "Dodati salatu i povrće na tortilju.", "Urolati i preseći."],
  },
  {
    id: "piletina-teriyaki",
    title: "Piletina teriyaki",
    short: "Piletina u soja-đumbir sosu, super ukusno i proteinski.",
    description: "Inspirisano azijskom kuhinjom, brzo se sprema u tiganju.",
    timeMin: 25,
    difficulty: "Srednje",
    category: "proteinsko",
    isPremium: false,
    imageUrl:"https://kaufland.media.schwarz/is/image/schwarz/savanovic%20kaufland%2010?JGstbGVnYWN5LW9uc2l0ZS02JA==",
    ingredients: ["Pileći file", "Soja sos", "Med (ili šećer)", "Đumbir", "Beli luk", "Susam (opciono)"],
    steps: ["Iseći piletinu na trakice.", "Zapeći piletinu na tiganju.", "Dodati soja sos + malo meda + đumbir + beli luk.", "Krčkati 3–5 min dok se sos ne zgusne."],
  },
  {
    id: "tofu-bowl",
    title: "Vegan tofu bowl",
    short: "Tofu + pirinač + brokoli, proteinski vegan klasik.",
    description: "Proteinski veganski obrok sa tofuom i povrćem.",
    timeMin: 30,
    difficulty: "Lako",
    category: "vegan",
    isPremium: false,
    imageUrl:"https://images.unsplash.com/photo-1623509636544-4cfcb1195b40?w=1200&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dG9mdSUyMGJvd2x8ZW58MHx8MHx8fDA%3D",
    ingredients: ["Tofu", "Pirinač", "Brokoli", "Soja sos"],
    steps: ["Ispržiti tofu.", "Skuvati pirinač.", "Sjediniti sve sastojke."],
  },
  {
    id: "veganska-pasta-pesto",
    title: "Veganska pasta sa pestom",
    short: "Pasta + pesto od bosiljka i indijskog oraha, brzo i mirisno.",
    description: "Brza veganska pasta sa domaćim pestom.",
    timeMin: 25,
    difficulty: "Lako",
    category: "vegan",
    isPremium: true,
    priceRsd: 229,
imageUrl:"https://www.foodiecrush.com/wp-content/uploads/2017/09/Pesto-Pasta-Recipe-foodiecrush.com-002.jpg",
    ingredients: ["Pasta", "Bosiljak", "Beli luk", "Maslinovo ulje", "Indijski orah"],
    steps: ["Skuvati pastu.", "Izblendati pesto.", "Pomešati pastu sa pestom."],
  },
  {
    id: "leblebije-curry",
    title: "Curry od leblebija",
    short: "Leblebije u kokos mleku sa curry začinom — jelo na kašiku.",
    description: "Začinjen veganski obrok na kašiku.",
    timeMin: 40,
    difficulty: "Srednje",
    category: "vegan",
    isPremium: false,
    imageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN3ihzP_2Yz2Q_OyxOgoYLxLZzFvJZTCB-Fg&s",
    ingredients: ["Leblebije", "Kokosovo mleko", "Curry začin", "Crni luk"],
    steps: ["Prodinstati luk.", "Dodati leblebije i začine.", "Dodati kokosovo mleko i kuvati."],
  },
  {
    id: "veganski-burger",
    title: "Veganski burger od pasulja",
    short: "Pljeskavice od pasulja + ovsene pahuljice, pečeno u tiganju.",
    description: "Zdrav veganski burger.",
    timeMin: 35,
    difficulty: "Srednje",
    category: "vegan",
    isPremium: true,
    priceRsd: 279,
    imageUrl:"https://www.aler.rs/wp-content/uploads/2025/08/Kako-napraviti-savrsen-veganski-burger-kod-kuce.png",
    ingredients: ["Crni pasulj", "Ovsene pahuljice", "Crni luk", "Začini"],
    steps: ["Izgnječiti pasulj.", "Dodati ostale sastojke.", "Formirati pljeskavice i ispeći."],
  },
  {
    id: "humus-sendvic",
    title: "Humus sendvič",
    short: "Humus + povrće u hlebu/tortilji — ultra brzo i ukusno.",
    description: "Veganski sendvič sa humusom i svežim povrćem.",
    timeMin: 8,
    difficulty: "Lako",
    category: "vegan",
    isPremium: false,
    imageUrl:"https://simple-veganista.com/wp-content/uploads/2012/07/best-hummus-veggie-sandwich-8.jpg",
    ingredients: ["Humus", "Integralni hleb ili tortilja", "Krastavac", "Paradajz", "Zelena salata", "So, biber"],
    steps: ["Namazati humus na hleb/tortilju.", "Dodati povrće.", "Preklopiti i poslužiti."],
  },
  {
    id: "salata-kinoa",
    title: "Kinoa salata",
    short: "Kinoa + povrće + limun, lagano i hranljivo.",
    description: "Osvežavajuća veganska salata sa kinoom.",
    timeMin: 25,
    difficulty: "Lako",
    category: "vegan",
    isPremium: true,
    priceRsd: 219,
    imageUrl:"https://recepti.zena.blic.rs/resources/images/36/36699df7f3303de7b42a8e821c8d2da0/resize/822e482c80b29cc688aa3643948a293a_670x0.jpg",
    ingredients: ["Kinoa", "Paradajz", "Krastavac", "Limun", "Maslinovo ulje", "So, biber"],
    steps: ["Skuvati kino u slanoj vodi i ohladiti.", "Iseckati povrće.", "Pomešati i dodati limun + ulje."],
  },
  {
    id: "krem-corba-bundeva",
    title: "Krem čorba od bundeve",
    short: "Bundeva + šargarepa + začini, izblendano kremasto.",
    description: "Topla veganska čorba, idealna za zimu.",
    timeMin: 35,
    difficulty: "Srednje",
    category: "vegan",
    isPremium: false,
    imageUrl:"https://crvena-jabuka.ba/wp-content/uploads/2023/01/CJ-Corba.jpg",
    ingredients: ["Bundeva", "Šargarepa", "Crni luk", "So, biber", "Maslinovo ulje"],
    steps: ["Prodinstati luk.", "Dodati bundevu i šargarepu, naliti vodom.", "Kuvati 20–25 min.", "Izblendati i začiniti."],
  },
  {
    id: "peceni-krompir-i-paprika",
    title: "Pečeni krompir i paprika",
    short: "Rerna obrok: krompir + paprika + začini, bez muke.",
    description: "Jednostavan veganski obrok iz rerne.",
    timeMin: 45,
    difficulty: "Lako",
    category: "vegan",
    isPremium: true,
    priceRsd: 189,
    imageUrl:"https://hips.hearstapps.com/hmg-prod/images/roasted-potatoes-lead-66b12d40121ff.jpg?crop=1xw:1xh;center,top&resize=1400:*",
    ingredients: ["Krompir", "Paprika", "Maslinovo ulje", "So, biber", "Aleva paprika"],
    steps: ["Iseći krompir i papriku.", "Začiniti i dodati malo ulja.", "Peći 35–40 min na 200°C."],
  },
];
